services:
  - type: web
    name: ai-interview-simulator
    env: java
    plan: free
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    autoDeploy: true
